### ISSUE TITLE
What is schildichat-desktop and how does it differ from standard Element?

### ISSUE THREAD

**Issue by cloudrac3r** [SpiritCroc/schildichat-desktop#1]
I'd like to know what's different so I can decide whether I will enjoy using this application or not.

**Comment by SpiritCroc** [comment]
It's a fork of element web/desktop with similar design approaches like SchildiChat-Android compared to Element-Android (i.e. message bubbles and an unified chat list instead of separated rooms and direct chats).
There is no release yet. Once there is, I'll update the README and post on TWIM. Maybe later this week or next week. It's still more of a proof-of-concept than a finished product though, and I probably won't put as much work in it as in the Android variant.

**Comment by cloudrac3r** [comment]
Sounds interesting, I'll check back later and try it out when there's s release.

**Comment by SpiritCroc** [comment]
The README has been updated.
